### ISSUE TITLE
What is valid text input for markovify.Text?

### ISSUE THREAD

**Issue by balajikvijayan** [jsvine/markovify#10]
I'm trying out this functionality in conjunction with gensim's doc2vec (https://github.com/piskvorky/gensim/blob/develop/docs/notebooks/doc2vec-IMDB.ipynb) I'm getting an error when I try to utilize the ACL IMDB prepared text from the gensim example. I've attached a sample document (sandbox.txt) that causes this error as well as 2 samples that work (jayz.txt & sherlock.txt)

I'd like to identify what the difference is between these files that triggers the error in 1 but not the other two. Thanks!

[jayz.txt](https://github.com/jsvine/markovify/files/56036/jayz.txt)
[sandbox.txt](https://github.com/jsvine/markovify/files/56037/sandbox.txt)
[sherlock.txt](https://github.com/jsvine/markovify/files/56038/sherlock.txt)

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-45-e4083c9cead6> in <module>()
      4     text = f.read()
      5 
----> 6 testModel = markovify.Text(text)
      7 tool = grammar_check.LanguageTool("en-US")
      8 

C:\Anaconda\lib\site-packages\markovify\text.pyc in __init__(self, input_text, state_size, chain)
     22         self.rejoined_text = self.sentence_join(map(self.word_join, runs))
     23         state_size = state_size or 2
---> 24         self.chain = chain or Chain(runs, state_size)
     25 
     26     def sentence_split(self, text):

C:\Anaconda\lib\site-packages\markovify\chain.pyc in __init__(self, corpus, state_size, model)
     36         """
     37         self.state_size = state_size
---> 38         self.model = model or self.build(corpus, self.state_size)
     39 
     40     def build(self, corpus, state_size):

C:\Anaconda\lib\site-packages\markovify\chain.pyc in build(self, corpus, state_size)
     46         appears.
     47         """
---> 48         if (type(corpus) != list) or (type(corpus[0]) != list):
     49             raise Exception("`corpus` must be list of lists")
     50 

IndexError: list index out of range

**Comment by jsvine** [comment]
Strange. This seems to work for me: http://nbviewer.ipython.org/gist/jsvine/75479c027dae4af14f5a/markovify-test.ipynb

Perhaps it's something about executing this on a non-Unix machine? Something about newlines or carriage returns? I'm a bit stumped.

One difference between the first file and the other two is that the first text file contains only one line. What happens if you copy that line, so that you have two lines in that file?

**Comment by balajikvijayan** [comment]
Non UNIX is probably in play (classic Windows). I found the cause as the split sentence function not catching sentences beginning with lower case letters. Swapping in NLTK's punkt tokenize sentences function did the trick. If you want that functionality added I'm happy to submit a pr. Thanks for taking a look!

**Comment by jsvine** [comment]
Thanks! I'd rather keep NLTK out of the requirements, if possible. I'll look into the sentence-splitter, and see what might be causing it to act differently on Unix vs. Windows machines.
