### ISSUE TITLE
multiple sentences?

### ISSUE THREAD

**Issue by andrewwlong** [jsvine/markovify#101]
Perhaps I am missing something, but is there a way to create multiple sentences? I was able to use the example code to create individual sentences, but when I put two sentences next to each other they seem massively disjointed. Just wondering if there is a way to generate a paragraph.

**Comment by jsvine** [comment]
The conceptual model and target output for `markovify.Text` is a single sentence. If your corpus separates paragraphs with newlines, you could likely achieve your goal by using [`markovify.NewlineText`](https://github.com/jsvine/markovify/blob/master/markovify/text.py#L258).

If that doesn't quite do the trick for you, then you could [extend `markovify.Text.sentence_split`](https://github.com/jsvine/markovify#extending-markovifytext) to reframe the core concept to capture whatever a paragraph looks like in your corpus.
