### ISSUE TITLE
make_sentence never succeeds with seemingly normal input

### ISSUE THREAD

**Issue by Lynnesbian** [jsvine/markovify#103]
This is the corpus, which always fails: https://my.mixtape.moe/synvpe.txt
This is a slightly modified corpus, which always succeeds, but always gives the same output: https://my.mixtape.moe/yrlbvb.txt
This is the code i'm using to to test the markov output:
```
#!/usr/bin/env python3
import markovify

toots_str = open("tootstr.txt", "r").read()
model = markovify.NewlineText(toots_str)
print(model.make_sentence(tries=100000))
```

Is there anything I'm doing wrong here? I'm using this code to create a bot. I've created over a dozen other bots using the exact same source code, and this is the first to have this issue.

**Comment by npeirson** [comment]
generally these sorts of problems are caused by unexpected encodings. Guessing it needs to be UTF8, but can't test it for ya from the mobile app.

**Comment by Lynnesbian** [comment]
Thank you for the quick response! I just tried using UTF-8 to read the file, and I still got the same issue.

**Comment by jsvine** [comment]
Howdy. Can you re-upload the corpus? I'm getting a 404. 

But, blindly guessing, is it possible that perhaps there are no newlines in the corpus?

**Comment by Lynnesbian** [comment]
I think I found out why, actually. The corpus didn't contain enough words for markovify to be able to use anything.
