### ISSUE TITLE
Seed first word of sentence

### ISSUE THREAD

**Issue by Green-Wolf** [jsvine/markovify#108]
Hello,

I was just wondering if it is possible to seed the first word of the sentence you want to create? 

So I can have my sentence always start with the word I want? 

Many thanks!

**Comment by jsvine** [comment]
Yes, that's possible by passing the `init_state` argument to `.make_sentence(...)`: https://github.com/jsvine/markovify/blob/c41af53ea3b5dfbb693e48a71803f6fd280c71a4/markovify/text.py#L150-L160

**Comment by Green-Wolf** [comment]
Thank you very much!
