### ISSUE TITLE
Something similar to begins with

### ISSUE THREAD

**Issue by raunakdaga** [jsvine/markovify#109]
Hi, this may be the wrong place to open this issue as it is more of a question/feature request, but is their anyway to make something similar to the make sentence beginning with method that makes a sentence ending with a certain string? Someone told me I could just use the beginning with sentence and reverse it, but the grammar would then be completely off I am sure. Is their a way to make it so that it creates a sentence that ENDS with a certain string? Any help would be greatly greatly appreciate. Thank you :)

**Comment by jsvine** [comment]
Due to the nature of Markov chains, I don't think it's possible to
*guarantee* that a sentence ends with a string. You could, however,
generate many sentences and keep only those that end with the string that
you want.

**Comment by raunakdaga** [comment]
That's what I ended up doing to fix my problem. Unfortunately, this greatly
slows down the process, but I can't think of another workaround.
