### ISSUE TITLE
Exclude sentences that match the source text exactly

### ISSUE THREAD

**Issue by katacarbix** [jsvine/markovify#114]
Every so often `make_short_sentence()` generates a sentence that is directly from the corpus. I could make a loop to check until it doesn't match, but is there an easier way?

**Comment by jsvine** [comment]
Hi, @katacarbix. That's odd. Markovify should already be doing that. Per the readme: 

> By default, `markovify.Text` tries to generate sentences that do not simply regurgitate chunks of the original text. The default rule is to suppress any generated sentences that exactly overlaps the original text by 15 words or 70% of the sentence's word count. You can change this rule by passing `max_overlap_ratio` and/or `max_overlap_total` to the `make_sentence` method. Alternatively, this check can be disabled entirely by passing `test_output` as False.

It's possible that there's a bug in the code corresponding to that logic. Do you have an example of a corpus and code that reproduces this problem?

**Comment by jsvine** [comment]
Hi @katacarbix, just checking on this again. Thanks!

**Comment by katacarbix** [comment]
I'm no longer working on the project, sorry.
