### ISSUE TITLE
make_sentence_that_contains

### ISSUE THREAD

**Issue by voltaxvoltax** [jsvine/markovify#122]
I'm sorry to re-open this Feature Request (https://github.com/jsvine/markovify/issues/52),  but I've been trying the solution approach of using the while loop and with a corpus of 6mb it takes almost 30 seconds (or more) to generate a sentence containing the specific word.
It's somehow possible for you to implement this feature in code so it would be more fast to create sentences?

Thank you very much, and continue the good work!

**Comment by jsvine** [comment]
Closing this issue in favor of continuing the discussion in the original thread, where there’s more context.
