### ISSUE TITLE
Model portability 

### ISSUE THREAD

**Issue by zllovesuki** [jsvine/markovify#124]
Hi, I was wondering how difficult it would be to extend the underlying classes, so that the model can be stored, say, redis.

**Comment by jsvine** [comment]
Hi, and thanks for your interest in this library. The underlying classes are indeed meant to be extended, so that you can add functionality like that. If you're looking to add importers/exporters, you could take inspiration from `Chain.to_json(...)` and `Chain.from_json(...)`.
