### ISSUE TITLE
Example of how to use .make_sentence(init_state = something)?

### ISSUE THREAD

**Issue by JGCoelho** [jsvine/markovify#125]
What exactly must be the format of the something? I tried putting a string of a word, putting a tuple with the word, putting a list with the word. Despite trying a lot of formats i keep getting this error

```
line 213, in make_sentence
    words = prefix + self.chain.walk(init_state)
  File "C:\Users\JGC\AppData\Local\Programs\Python\Python37\lib\site-packages\markovify\chain.py", line 137, in walk
    return list(self.gen(init_state))
  File "C:\Users\JGC\AppData\Local\Programs\Python\Python37\lib\site-packages\markovify\chain.py", line 126, in gen
    next_word = self.move(state)
  File "C:\Users\JGC\AppData\Local\Programs\Python\Python37\lib\site-packages\markovify\chain.py", line 112, in move
    choices, weights = zip(*self.model[state].items())
KeyError: 'was'
```

I'm using markovify 0.8.0 on a python 3.7 environment.

**Comment by jsvine** [comment]
It's difficult to debug this without the code and the corpus you're using. Can you provide that?

**Comment by JGCoelho** [comment]
Sorry, forgot to include the code. I was trying to make a short sentence with a start, like that:

```python
text = open("samples\\asoiaf.txt","r",encoding = "utf-8")
model = markovify.Text(text)
model.make_short_sentence(init_state = "was", max_chars = 40)
```

But i have noticed the error: only make_sentence has a parameter init_state, this parameter doesn't exists inside make_short_sentence, hence the error. So i guess i will need to override this method to introduce a new parameter.
