### ISSUE TITLE
Merge models

### ISSUE THREAD

**Issue by emreaypar** [jsvine/markovify#13]
Hi, if i have separate models built and saved as json, how can i merge them before generating a sentence?
Thanks

**Comment by jsvine** [comment]
Hi @emreaypar, really interesting question. Right now, `markovify` doesn't provide a method for doing this. But it should, at least in theory, be feasible. How do you envision it working? Something like the following?:

```python
import markovify
import json

model_a = json.load(open("path/to/model_a.json"))
model_b = json.load(open("path/to/model_b.json"))

model_combined = markovify.combine([ model_a, model_b ])

chain = markovify.Text.from_json(model_combined)
```

Or another way?

**Comment by emreaypar** [comment]
exactly like you mentioned.
i'm using markovify for poetry and i think i need switch/merge/add/remove
operations for corpora.

On Wednesday, 30 March 2016, Jeremy Singer-Vine <notifications@github.com>
wrote:

> Hi @emreaypar <https://github.com/emreaypar>, really interesting
> question. Right now, markovify doesn't provide a method for doing this.
> But it should, at least in theory, be feasible. How do you envision it
> working? Something like the following?:
>
> import markovifyimport json
>
> model_a = json.load(open("path/to/model_a.json"))
> model_b = json.load(open("path/to/model_b.json"))
>
> model_combined = markovify.combine([ model_a, model_b ])
>
> chain = markovify.Text.from_json(model_combined)
>
> Or another way?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/jsvine/markovify/issues/13#issuecomment-203197316>
>


-- 
-ea

**Comment by jsvine** [comment]
Neat, and makes sense. I'll try adding that sometime soon. Great idea.

**Comment by emreaypar** [comment]
great, thanks.

On Wednesday, 30 March 2016, Jeremy Singer-Vine <notifications@github.com>
wrote:

> Neat, and makes sense. I'll try adding that sometime soon. Great idea.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/jsvine/markovify/issues/13#issuecomment-203452983>
>


-- 
-ea

**Comment by jsvine** [comment]
Added this feature in v0.3.0: https://github.com/jsvine/markovify/pull/14

`pip install markovify --upgrade` should get you the new version. Curious to see what you make with it!

**Comment by emreaypar** [comment]
yay! i'm curious too... thanks.
