### ISSUE TITLE
"None" is present multiple times in generated text

### ISSUE THREAD

**Issue by WiseMatthack** [jsvine/markovify#136]
When generating a text using `markovify.NewlineText`, the generated sentences often contains "None", why is it present? My corpus used for the model doesn't contain any blank line.

**Comment by Freestackmejai** [comment]
Can you please provide the corpus ? 
And the steps to reproduce ?

**Comment by WiseMatthack** [comment]
Sure, here is the corpus and the .py file. You just need to generate a few texts and sometimes "None" will appear in them.
[queen.txt](https://github.com/jsvine/markovify/files/4840559/queen.txt)
[queen-gen.py](https://matthack.s-ul.eu/ahfBLmau)

**Comment by jsvine** [comment]
Hi @WiseMatthack, thanks for your interest in the library.  And thanks @Freestackmejai for the request for the demo. I appreciate both. Per the ["Basic Usage" notes](https://github.com/jsvine/markovify#basic-usage):
 
- By default, the `make_sentence` method tries a maximum of 10 times per invocation, to make a sentence that does not overlap too much with the original text. If it is successful, the method returns the sentence as a string. If not, it returns `None`. To increase or decrease the number of attempts, use the `tries` keyword argument, e.g., call `.make_sentence(tries=100)`.

I believe this answers your question, so I'm closing this issue. But let me know if I've misunderstood and we can reopen.
