### ISSUE TITLE
Add support for non-english characters

### ISSUE THREAD

**Issue by abiaus** [jsvine/markovify#139]
Every time I run the chain I have issues with Spanish accents such as "á","é","í","ó","ú" and also "ñ".

I believe the issue is in the "splitters.py" file where you declare `ascii_lowercase = "abcdefghijklmnopqrstuvwxyz"`

Maybe if the line said something like `unicode_lowercase = "aábcdéfghíjklmnñoópqrstuúvwxyz"`

Would that work? I don't know how to try it

**Comment by Findus23** [comment]
Just in case you don't know it: You don't have to use the built-in functions to split text into a list and join it back together: https://github.com/jsvine/markovify#advanced-usage

In https://se-simulator.lw1.at/ I am using the MosesTokenizer and Detokenizer and it doesn't work that bad: https://github.com/Findus23/se-simulator/blob/master/markov.py

**Comment by abiaus** [comment]
I ended up replacing those characters with accents to the same without an accent. **á->a**

Not the best solution but an acceptable workaround

**Comment by jsvine** [comment]
Good point, and thank you for the suggestion @abiaus. Now available in v0.8.3: We checked for the Unicode `[A-Za-z]` regular expression ranges, which should include all accented characters, rather than explicit lists.
