### ISSUE TITLE
Character level chains instead of word level?

### ISSUE THREAD

**Issue by MrDowntempo** [jsvine/markovify#147]
This would be a useful feature to generate new names or words instead of sentences, if given a list of names or words as a corpus.

**Comment by jsvine** [comment]
I haven't tried that before, but you *should* be able to achieve this through the extensible `markovify.Chain` class, doing something like:

```python
corpus = [ list(word) for word in my_list_of_words ]
chain = markovify.Chain(corpus, state_size = 3)  # You might want to experiment with the state size
example_output = chain.walk()
print(example_output)
```

Does that work for you?

**Comment by jsvine** [comment]
Closing due to lack of response.
