### ISSUE TITLE
Thank you for a job well done!

### ISSUE THREAD

**Issue by asigalov61** [jsvine/markovify#151]
Hello, @jsvine and all users of markovify!

I just wanted to express my gratitude for this awesome Markov chain implementation and I wanted to share with you the result I achieved thanks to it.

https://github.com/asigalov61/Markovify-Piano

I hope you will enjoy it and find it inspiring :)

Most sincerely,

Alex

**Comment by IThinkImOKAY** [comment]
thank you, devs!

**Comment by jsvine** [comment]
Very fun, and thanks for the kind words! Feel free to submit a PR to add this to the README's "Markovify In The Wild" section.
