### ISSUE TITLE
I can’t install because of the encoding of the file

### ISSUE THREAD

**Issue by ZYPmaster** [jsvine/markovify#154]
I want to use your module, but I cannot install it using pip.This may be because the default encoding of my computer is not utf-8
Add parameter "encoding='UTF-8' " in "open(path,encoding='UTF-8')"in setup.py will work.

**Comment by jsvine** [comment]
Thanks for noting. I'll plan to adjust that. In the meantime, this may work for you:

```sh
LANG=en_US.UTF-8 pip install markovify
```
