### ISSUE TITLE
Can I generate sentence with only two words? 

### ISSUE THREAD

**Issue by deethereal** [jsvine/markovify#157]
If I try to call  
`` text_model = markovify.Text(text, state_size=1)
text_model.make_sentence_with_start(word,strict=True,min_words=2,max_words=3)``
I will get only sentence length of 3 words or ``Param.Error``

**Comment by deethereal** [comment]
I think I found the problem: ``max_overlap_ratio=0.7`` forbid me to generate 2-words-sentences.
But I still have a question: should I format text like ``Word1 word2 word3.`` or ``Word1 word2 word3 .`` for the best result?

**Comment by jsvine** [comment]
>  But I still have a question: should I format text like `Word1 word2 word3.` or `Word1 word2 word3 .` for the best result?

 `Word1 word2 word3.` will probably be the most reliable.

Alternatively, you can place each sentence on a new line, and use `markovify.NewlineText` instead of `markovify.Text` (see notes section [here](https://github.com/jsvine/markovify#basic-usage)).
