### ISSUE TITLE
generate sentence with it's prediction

### ISSUE THREAD

**Issue by roiDaniela** [jsvine/markovify#158]
Is it possible to get top n possible sentences with their probability? thanks

**Comment by SudhanshuBlaze** [comment]
Same doubt, can we do it? @roiDaniela @jsvine

**Comment by jsvine** [comment]
Unless I'm misunderstanding the question, I believe what you're seeking is not easily calculable, given how Markov chains operate and the enormous number of possible sentences. You could, however, draw a very large sample of possible sentences, running `model.make_sentence()` repeatedly, and identify the sentences that are generated most frequently.
