### ISSUE TITLE
proper way to use to_json?

### ISSUE THREAD

**Issue by QuadCityCJ** [jsvine/markovify#16]
I am trying to generate a corpus with markovify and then save as json to file. Is this possible? I've been trying to use the generate_corpus() and to_json but keep getting an error that corpus must be a list of lists.

Thanks

**Comment by jsvine** [comment]
Happy to help. Can you post the code (or a generic version of it)?

**Comment by QuadCityCJ** [comment]
I actually think I have gotten it to work. My problem was that I was not passing a list of lists to the Chain class correctly. Once I've done that I was able to use .to_json()

**Comment by jsvine** [comment]
Glad to hear it!
