### ISSUE TITLE
“python_requires” should be set with “>=3.6”, as markovify 0.9.3 is not compatible with all Python versions.

### ISSUE THREAD

**Issue by PyVCEchecker** [jsvine/markovify#169]
Currently, the keyword argument **python_requires** of **setup()** is not set, and thus it is assumed that this distribution is compatible with all Python versions. 
However, I found it is not compatible with **Python<3.6**. My local Python version is 2.7, and I encounter the following error when executing _“pip install markovify”_ 

```
Collecting markovify
  Downloading markovify-0.9.3.tar.gz (28 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uBzbMQ/markovify/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uBzbMQ/markovify/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-uBzbMQ/markovify/pip-egg-info
         cwd: /tmp/pip-install-uBzbMQ/markovify/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-uBzbMQ/markovify/setup.py", line 15, in <module>
        with _open(NAME + "/__version__.py") as f:
      File "/tmp/pip-install-uBzbMQ/markovify/setup.py", line 12, in _open
        return open(path, encoding="utf-8")
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I found that **setup.py** used a Python3-specific keyword argument **encoding** for the function **open**, which lead to installation failure of Inject in Python2. I also noticed that **\_\_init\_\_.py** used the syntax feature __f-string__, and the feature is only compatible with Python 3.6 and above.

Way to fix:
modify **setup()** in **setup.py,** add **python_requires** keyword argument:
```python
setup(…
     python_requires='>=3.6',
     …)
```
Thanks for your attention.
Best regrads,
PyVCEchecker

**Comment by jsvine** [comment]
Thanks, and change now made 👍
