### ISSUE TITLE
Markovify returns None

### ISSUE THREAD

**Issue by AndreyRGW** [jsvine/markovify#185]
code:
```
import markovify

# Get raw text as string.
with open("c:/test/lrtext2.txt", encoding='utf-8') as f:
    text = f.read()

# Build the model.
text_model = markovify.Text(text, well_formed=False)

# Print five randomly-generated sentences
for i in range(5):
    print(text_model.make_sentence())

```

Output:
```
C:\test>C:/ProgramData/anaconda3/envs/MarkTest/python.exe "c:/test/markovify.py"
None
None
None
None
None
```

the contents of the file lrtext2.txt:
```
Лимитированная кока-кола с искусственным интеллектом

Энтузиаст утверждает, что у нее лимонный запах и ягодный вкус.

В комментариях пишут: компания взяла информацию о вкусовых трендах, прогнала их через ИИ-алгоритм и вывела эту лимитированную версию напитка
```

**Comment by jsvine** [comment]
With such a small corpus, it seems likely that `markovify` could not identify (within `tries=...`) a new sentence that did not substantially overlap with the original text. You might try tweaking the `tries` and `max_overlap_ratio` settings documented [here](https://github.com/jsvine/markovify?tab=readme-ov-file#basic-usage).

**Comment by AndreyRGW** [comment]
> With such a small corpus, it seems likely that `markovify` could not identify (within `tries=...`) a new sentence that did not substantially overlap with the original text. You might try tweaking the `tries` and `max_overlap_ratio` settings documented [here](https://github.com/jsvine/markovify?tab=readme-ov-file#basic-usage).

Setting the value to 1 for state_size seems to have worked for me. Thanks!

**Comment by jsvine** [comment]
Glad to hear it! (Note that `state_size=1` means that the model will just pick words at random, weighted by their frequency, rather than observing the word-follows-word patterns.)
