### ISSUE TITLE
NewlineText bug

### ISSUE THREAD

**Issue by aolko** [jsvine/markovify#22]
`AttributeError: 'module' object has no attribute 'NewlineText'` happes on text file with new lines
```py
import markovify

with open("phrases.txt") as f:
    content = f.read()

comment_model = markovify.NewlineText(content)
print(comment_model.make_sentence())
```

aaaand it won't open up text file even with `Text`. Returns `None`

**Comment by jsvine** [comment]
Good catch, and thanks. Added `NewlineText` to the main namespace, bumped the version to `0.3.2` and pushed to PyPi. If you run `pip install --upgrade markovify` and re-run your script, it should work. Let me know if not.

**Comment by aolko** [comment]
With `f.read()` it produces `none`. With `f.readlines()`:
```Py
Traceback (most recent call last):
  File "D:/************/t.py", line 14, in <module>
    comment_model = markovify.NewlineText(content)
  File "C:\Users\B\AppData\Local\Programs\Python\Python35-32\lib\site-packages\markovify-0.3.2-py3.5.egg\markovify\text.py", line 20, in __init__
    runs = list(self.generate_corpus(input_text))
  File "C:\Users\B\AppData\Local\Programs\Python\Python35-32\lib\site-packages\markovify-0.3.2-py3.5.egg\markovify\text.py", line 73, in generate_corpus
    sentences = self.sentence_split(text)
  File "C:\Users\B\AppData\Local\Programs\Python\Python35-32\lib\site-packages\markovify-0.3.2-py3.5.egg\markovify\text.py", line 158, in sentence_split
    return re.split(r"\s*\n\s*", text)
  File "C:\Users\B\AppData\Local\Programs\Python\Python35-32\lib\re.py", line 203, in split
    return _compile(pattern, flags).split(string, maxsplit)
TypeError: expected string or bytes-like object
```

**Comment by jsvine** [comment]
Hmmm, `f.read()` is the correct approach. There are a couple potential reasons you may be getting `None`: 

- Your corpus is too small, containing too few overlapping phrases.
- There's a bug in `NewlineText`

Could you email or upload `phrases.txt`? That'd help me figure out the problem.

**Comment by aolko** [comment]
a simple `phrases.txt`
```
1,2,3. This is a text. A new sample sentence.
```

**Comment by jsvine** [comment]
That looks to be the problem. To construct a new (and unique) sentence, a Markov chain needs a corpus that contains some degree of overlap between sequences of words. Try using a longer, more repetitive corpus. 

If you don't have one on hand, here's one that someone has previously used successfully: https://github.com/wragge/sekritfiles/blob/master/data/titles-33(1)(a).txt

**Comment by aolko** [comment]
but what if i want to make it less repetitive/more unique corpus?

**Comment by jsvine** [comment]
The nature of Markov chains — not specific to `markovify` — is that they require a certain amount of repetition to work well. In the case of textual Markov chains, this means words appear multiple times, in different contexts. If you're looking to generate text from a small corpus, composed mostly of only-appearing-once words, you'll probably want to use something other than a Markov chain.
