### ISSUE TITLE
markovify.combine(...) always returns a markovify.Text regardless of input type

### ISSUE THREAD

**Issue by tmsherman** [jsvine/markovify#23]
While all the inputs to markovify.combine must be the same class, and that class doesn't have to be a Text, the output is always a Text. This means that any methods I've overridden in my own custom class disappear when I combine two models. While not necessarily a bug, this should at least be noted or documented for combine().

**Comment by jsvine** [comment]
Hi Tim, and thanks! Great catch. I should make that method more flexible. Could you share the code you're using? (Either here or [via email](mailto:jsvine@gmail.com)?) With that, I can make sure that the modifications work.

Cheers,
Jeremy

**Comment by jsvine** [comment]
Hi, @tmsherman, just checking on this.
