### ISSUE TITLE
Issue with make_sentence_with_start

### ISSUE THREAD

**Issue by agincel** [jsvine/markovify#29]
File "/mnt/c/Users/Asdf/Documents/1 - Git/AsdfTestBot/src/atbMarkov.py", line 38, in getMarkov
    ret = builtins.markov.make_sentence_with_start(lastWord, tries=30)
  File "/usr/local/lib/python3.4/dist-packages/markovify/text.py", line 156, in make_sentence_with_start
    return self.make_sentence(init_state, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/markovify/text.py", line 124, in make_sentence
    words = prefix + self.chain.walk(init_state)
  File "/usr/local/lib/python3.4/dist-packages/markovify/chain.py", line 114, in walk
    return list(self.gen(init_state))
  File "/usr/local/lib/python3.4/dist-packages/markovify/chain.py", line 103, in gen
    next_word = self.move(state)
  File "/usr/local/lib/python3.4/dist-packages/markovify/chain.py", line 89, in move
    choices, weights = zip(*self.model[state].items())
KeyError: ('___BEGIN__', 'men')

I am always sending a single word -- I used the normal method to get the sentence "Men, all this stuff you hear about America not wanting to fight, wanting to fight, wanting to fight, wanting to stay out of him all the time if he expects to keep on advancing." I then used make_sentence_with_start("men", tries=30), and that stack trace above is the result. This happens for any word.

What am I doing wrong?

**Comment by jsvine** [comment]
Hi, @agincel. It appears that the problem is that no sentence in your corpus begins exactly with `men ` (all lowercase). By default, `markovify` is case-sensitive. Does running `make_sentence_with_start("Men", tries=30)` work?

**Comment by agincel** [comment]
Yep, that fixed it right up. Two quick questions:

Is there an easier way to check if a word/phrase appears in the corpus without trying to make a sentence and getting an error?

and is there any way to remove case-sensitivity?

Thank you very much!

**Comment by jsvine** [comment]
> Is there an easier way to check if a word/phrase appears in the corpus without trying to make a sentence and getting an error?

Yep! You could test the corpus directly, e.g.:

```python
my_corpus = open("sherlock.txt").read()
print("Men" in my_corpus)
```

Or you could inspect the markov model itself. The first step would be to obtain all the observed tuples (of `state_size` length):

```python
text = markovify.Text(open("sherlock.txt").read())
observed_tuples = text.chain.model.keys()
```

> and is there any way to remove case-sensitivity?

Yes, though it depends on your ultimate goal. If you're OK with the final output being all lowercase, then the simplest approach would be to lowercase the corpus before building the markov model:

```python
text = markovify.Text(open("sherlock.txt").read().lower())
```
