### ISSUE TITLE
"All `models` must be of the same type."

### ISSUE THREAD

**Issue by bfontaine** [jsvine/markovify#32]
Hello,

There’s currently [a check in `utils.combine`](https://github.com/jsvine/markovify/blob/34b4a8cd1bd570ee47451aeaf9f0a799b28ccd77/markovify/utils.py#L29) that raises an exception if all models are not of the same type. Given that `get_model_dict` is called on each model why do we need to assert that all models are of the same type?

My problem is that I inherit classes from `Text` and `type(my_model)` doesn’t take that into account. See a minimal example below:

```python
class MyText(markovify.Text):
    pass

class MyOtherText(MyText):
    pass

markovify.combine([MyText("foo"), MyOtherText("bar")])
# Raises: ValueError: All `models` must be of the same type.
```

**Comment by jsvine** [comment]
Hi @bfontaine, and good question. 

> Given that get_model_dict is called on each model why do we need to assert that all models are of the same type?

`utils.combine` aims to return to you [an object of the same class as it received](https://github.com/jsvine/markovify/blob/master/markovify/utils.py#L47). If it receives two different classes of objects, it doesn't know what to return.

> My problem is that I inherit classes from Text and type(my_model) doesn’t take that into account. 

One way to accommodate this is to call `utils.combine` on the underlying `Chain` instances. E.g., using your example:

```python
class MyText(markovify.Text):
    pass

class MyOtherText(MyText):
    pass

t1 = MyText("foo")
t2 = MyOtherText("bar")

t_combined = MyText.from_chain(markovify.combine([ t1.chain, t2.chain ]).to_json())
```

**Comment by bfontaine** [comment]
Thanks, I’ll do something like that! I’d like to avoid that JSON serialization+deserialization step but the idea stays the same.
