### ISSUE TITLE
how can i use this to generate first order markov chain number 

### ISSUE THREAD

**Issue by jayjayram** [jsvine/markovify#33]
I want to generate first order markov chain by giving randomly generated number sequence x=[5 6 1 6 4 1 2 4 6 6 1 6 6 3 5 1 3 6 5 6 4 1 6 6 5 5 5 3 4 2] as input. how to do this.

**Comment by jsvine** [comment]
Try this:

```python
chain = markovify.Chain([ x ], state_size=1)
print(list(chain.gen()))
```

**Comment by jayjayram** [comment]
I don't know which file I should have to copy and where to add above mentioned lines.

**Comment by jsvine** [comment]
I don't understand the question. Could you elaborate?

**Comment by jayjayram** [comment]
```
chain = markovify.Chain([ x ], state_size=1)
print(list(chain.gen()))
```

This  two lines only give output with given x in python, or I have copy paste above two lines in  any file of this markovify project.

**Comment by jsvine** [comment]
Ah, I see. Here's a full script that should work, using the `x` you referenced in your initial comment:

```python
import markovify
x = [5, 6, 1, 6, 4, 1, 2, 4, 6, 6, 1, 6, 6, 3, 5, 1, 3, 6, 5, 6, 4, 1, 6, 6, 5, 5, 5, 3, 4, 2]
chain = markovify.Chain([ x ], state_size=1)
print(list(chain.gen()))
```
