### ISSUE TITLE
Question about storing models as JSON

### ISSUE THREAD

**Issue by ammgws** [jsvine/markovify#36]
The readme mentions :

> Models can be stored as JSON, allowing you to cache your results and save them for later.

Just to clarify, is this is only referring to markovify.Chain instances? Looking at the source I can only find methods for loading a Markov chain from a file/object, but not for a markovify.Text models.

**Comment by jsvine** [comment]
That's correct, and my apologies for the imprecision in the README.md. I'll aim to update that language soon. Thanks!

**Comment by ammgws** [comment]
Cheers for the clarification.
I was interested in speeding up the model generation, and loading a pregenerated chain file saved about 90s on my hardware, but I wanted to see how much further I could take it.
