### ISSUE TITLE
Question about combining models

### ISSUE THREAD

**Issue by anjabeth** [jsvine/markovify#37]
If I do markovify.combine() with no weighting, is it effectively the same as training one model on the texts of all the combined models? Asking because I'd like to train a model on a lot of text files, and it works out easier to create a bunch of different ones and then combine them, as long as that works the way I'm expecting it to.

**Comment by anjabeth** [comment]
Clarifying: I've been playing around with "combine" and have gotten it to work, but I'm curious - when it "combines" the models with weighting, is it just using those weights to choose which corpus the words come from, or do the corpuses actually mix? (For example, if I trained a model on the KJV and Moby Dick, could I get sentences that combine both texts? Or would I just get the right fraction of sentences that come from each text?)

**Comment by jsvine** [comment]
> If I do markovify.combine() with no weighting, is it effectively the same as training one model on the texts of all the combined models?

Yep!

> I'm curious - when it "combines" the models with weighting, is it just using those weights to choose which corpus the words come from, or do the corpuses actually mix?

The latter. The corpuses are, effectively, mixed.

> For example, if I trained a model on the KJV and Moby Dick, could I get sentences that combine both texts?

Yep! That's what should happen. (Would be curious to see the output.)

> Or would I just get the right fraction of sentences that come from each text?

Nope! There's currently no way to do that with `markovify`.

**Comment by anjabeth** [comment]
Thanks so much! That's what I was guessing - I think the length difference between the texts was just giving me lots more Bible words, but I wanted to make sure that it wasn't a weighting mistake. 

KJV/Moby Dick didn't produce anything terribly interesting on the couple of test runs I did (I'm currently just setting up the skeleton of my project), but I got some pretty fun results with Moby Dick + Pride and Prejudice:
```
"I was sure you could not be married all day"
"The envelope contained a sheet of blubber."
"Hold the steak in one hand, and a still slighter shuffling of women's shoes, and all was soon right again."
```

**Comment by jsvine** [comment]
Love those examples. Thanks for sharing!
