### ISSUE TITLE
Problems with json exporting

### ISSUE THREAD

**Issue by wodim** [jsvine/markovify#42]
1. The README mentions `markovify.Text.from_json()`, which doesn't exist -- should be something like `markovify.Text.from_chain(markovify.Chain.from_json())`.

2. If you use `text_model = markovify.NewlineText(text, state_size=3)`, export it as json and then load it back, when you use `text_model.make_short_sentence(140)` you get verbatim sentences out of the corpus. My corpus is composed of lines with fewer than 140 characters, but in any case, if I don't export the text_model to json and then load it back, sentences are generated correctly.

**Comment by jsvine** [comment]
My apologies, and great catch. I've updated the README to fix that section and add a more explicit example. Does following that example work for you? (You should be able to swap `markovify.Text` for `markovify.NewlineText`.)

**Comment by wodim** [comment]
Why do you still need the corpus text when reconstituting the model? Isn't everything inside the json file?

**Comment by jsvine** [comment]
The JSON file contains only the chain, rather than the full model (i.e., corpus + state_size + chain). But I could definitely imagine adding a feature to export/import full model. In fact, I'll try doing that right now.

**Comment by jsvine** [comment]
Done! See https://github.com/jsvine/markovify/pull/44, now merged into `master` and available on PyPi in `v0.5.0`.

**Comment by wodim** [comment]
Hm, that's fine, but there's a problem -- despite the names of the methods (from_json/to_json) those methods don't accept/return a str containing json, but a dict.

**Comment by jsvine** [comment]
Ah, I see. That's a good point. I suppose it'd make sense to do this:

- `.to_json`/`.from_json`: accepts/returns JSON strings.
- `.to_dict`/`.from_dict`: accepts/returns dicts.

What do you think?

**Comment by wodim** [comment]
That sounds good.

**Comment by jsvine** [comment]
Here's the proposed change: https://github.com/jsvine/markovify/pull/45/files

Along the lines of what you were thinking?

**Comment by wodim** [comment]
Yes. I personally don't like the idea of "to_json" to be honest, because the user should be left with the task of serialising the stuff (I'm using `pickle` myself because I imagine it's faster) but I guess it's a good idea to have those methods for consistency with what there is in markovify.Chain. It can't hurt.

**Comment by jsvine** [comment]
Makes sense, and thanks again for these suggestions. Much appreciated!

**Comment by wodim** [comment]
That's right, thanks for your work.
