### ISSUE TITLE
POSified text conflicting with json?

### ISSUE THREAD

**Issue by agladman** [jsvine/markovify#46]
I'm working on having my text_model save to/load from json. If I use `text_model = markovify.Text(foo)` everything works OK, but if I use `text_model = POSifiedText(foo)`, after reconstituting it back from json I get output like this:

I::PRP want::VBP to::TO share::NN it::PRP with::IN whomever::NN wants::VBZ it.::JJ

**Comment by jsvine** [comment]
Thanks for flagging, @agladman. Can you share the full code — or a working simplification of it — and the input text?

**Comment by agladman** [comment]
Here's a simplified version that illustrates the behaviour: https://github.com/agladman/simplified

**Comment by jsvine** [comment]
Thanks, that's very helpful. Changing [line 46 in simplified.py](https://github.com/agladman/simplified/blob/master/simplified.py#L46) from this:

```python
reconstituted_model = markovify.Text.from_json(model_data)
```
... to this:

```python
reconstituted_model = POSifiedText.from_json(model_data)
```

... seems to do the trick for me. Does that work for you? And does that resolve your general question?

**Comment by agladman** [comment]
Yes, that does the trick for me too. Thanks for looking into it.

**Comment by jsvine** [comment]
Great, and no problem.
