### ISSUE TITLE
Feature Suggestions:

### ISSUE THREAD

**Issue by thecerial** [jsvine/markovify#53]
1. Adjustable Word Weights:

Project https://github.com/G3Kappa/Adjustable-Markov-Chains/blob/master/markovchain.py#L174 has different functions to adjust the weights of words in the created output markov stream 

2. Beam Search:

Does it make sense to add Beam search to Normal Markov Chains?

Thank you for reading.

**Comment by amirouche** [comment]
@thecerial what do you mean by beam search?

**Comment by kittenswolf** [comment]
https://en.wikipedia.org/wiki/Beam_search, probably.

**Comment by jsvine** [comment]
I don't currently plan on adding these features, but appreciate you raising the ideas.
