### ISSUE TITLE
Feature Request: Sentence segmentation and word tokenization by SEGTOK

### ISSUE THREAD

**Issue by thecerial** [jsvine/markovify#64]
[https://github.com/fnl/segtok](url)

Provides fast & stable Sentence segmentation.

What do you think?

**Comment by jsvine** [comment]
Looks handy! Have you seen any benchmarks/comparisons of Segtok's segmentation/tokenizing vs. other implementations?

**Comment by GiantsLoveDeathMetal** [comment]
@thecerial [Page](https://github.com/fnl/segtok) not found?

**Comment by amirouche** [comment]
this link works: https://github.com/fnl/segtok

**Comment by jsvine** [comment]
I don't currently plan to add this as a core feature of Markovify, but you should be use Segtok for your projects by subclassing `markovify.Text` and overriding its `.sentence_split(...)` method: https://github.com/jsvine/markovify/blob/v0.7.1/markovify/text.py#L72-L76
