### ISSUE TITLE
Your definition of Markov states is problematic

### ISSUE THREAD

**Issue by Suyuanhang** [jsvine/markovify#67]
I noticed that in chain.py --> line 66, you defined your "follow" as a single element in a "run". 

However, the real state could be a bigram or ngram depends on the state-size. So clearly there is a mismatch between the current state and the following state that it is transiting to. 

Did I misunderstand you?

**Comment by jsvine** [comment]
I think you may be misunderstanding. Regardless of the `state_size`, the Markov chain will want to know what next *single* elements are valid. 

For instance, take this minimalist corpus, consisting of a single "run":

```python
c = [ [ "A", "B", "C", "D", "C", "C", "A", "B", "C" ] ]
```

And let's say we're just starting to generate the model, and `state_size == 2`, so the current state is `("A", "B")`. 

To properly generate the model, we'll want to know the next single element (`"C"`), not the next `state_size`-length tuple (`("C", "D")`).

Or perhaps *I* am misunderstanding *you*?

**Comment by Suyuanhang** [comment]
@jsvine Thanks for the feedback, I do think you messed up the concept of "state" in your implementation.
              In your example, the bigram states are: "AB","BC","CD","DC","CC", and "CA" if state size is two.
              However, the single-gram states are simply: "A","B","C", and "D"
             For 3-gram case, the states are: "ABC","BCD","CDC","DCC","CCA","CAB",and "ABC". 
            You can generalize the rule in other cases.
              So the total possible states are subject to the state size one choose, in language processing, it is usually called ngram technique.
              Since your markov model is first-order, you need to be careful with the definition of state, and unless you can draw a square state transition matrix from your model (and in your implementation, I couldn't), then there is a problem.
               You need to fix this

**Comment by Suyuanhang** [comment]
@jsvine I think you need to change chain.py -->line 66 to:
follow = items[i+1:i+state_size+1] #plus one since it is a first order Markov model

you may need to do necessary change in other places as well, I haven't go through your code.

**Comment by Suyuanhang** [comment]
@jsvine Basically, your implementation is largely correct if state size is one, it is not strictly correct otherwise

**Comment by jsvine** [comment]
Thanks, @Suyuanhang. I think, however, you might be misinterpreting that chunk of code in `chain.py`. 

> In your example, the bigram states are: "AB","BC","CD","DC","CC", and "CA" if state size is two.

In `markovify`, the states are represented as tuples. So your bigram example of `"AB"` is equivalent, in the code, to my bigram example of `("A", "B")`.

If you still think there's something wrong, I think it'd help if you could share a bit of working code that outputs the difference between what the library *should* produce and where you think it fails.

**Comment by Suyuanhang** [comment]
@jsvine Sure, I just want to raise this issue, I may misunderstand your program which indeed implement the ngram thing.

**Comment by jsvine** [comment]
Just checking back on this. Did you have a code example that demonstrates what you think is incorrect with the library?

**Comment by Suyuanhang** [comment]
@jsvine Not yet, I haven't got time to look back your code. Will update if I do find time. Thanks for reminding me anyway.
