### ISSUE TITLE
small datasets

### ISSUE THREAD

**Issue by rcrimp** [jsvine/markovify#70]
I've constructed a VERY small corpus of sentences.

> **I like** you
> you **like pie**

From these, I thought I would be able to generate

> **I like pie**

but `make_sentence(test_output=False)` only generates the two sentences which are in the original corpus.

**Comment by vkazanov** [comment]
What is the length of the chain you use?

**Comment by rcrimp** [comment]
Heres my code snippet

```python
import markovify

text = "I like you\nyou like pie"
text_model = markovify.NewlineText(text)

for i in range(10000):
    sentence = text_model.make_sentence(test_output=False)
    if sentence not in text.split('\n'):
        print(sentence)

print(text_model.chain.to_json())
```


which prints no sentences, only the chain at the end (as JSON)

> [[["___BEGIN__", "___BEGIN__"], {"I": 1, "you": 1}], [["___BEGIN__", "I"], {"like": 1}], [["I", "like"], {"you": 1}], [["like", "you"], {"___END__": 1}], [["___BEGIN__", "you"], {"like": 1}], [["you", "like"], {"pie": 1}], [["like", "pie"], {"___END__": 1}]]

**Comment by vkazanov** [comment]
I am not a developer of the library, but AFAIK you should do something like the following:

```python
markovify.NewlineText(text, state_size=1)
```

**Comment by rcrimp** [comment]
Exactly what I needed, thank you :)
