### ISSUE TITLE
Creating chains from very large files.

### ISSUE THREAD

**Issue by rivermont** [jsvine/markovify#74]
I am working on a project for generating HTML pages from a Markov chain. My current process is to copy the text of all `.html` pages in a folder into a single `.txt` file, then create a Markov model from that file.

The problem with this is that markovify loads the entire file into memory to create the model, and I have ~50GB of files.

Is there any way to create the model line-by-line / in chunks / read from disk instead of the whole thing at once?

**Comment by jsvine** [comment]
Hi Will. Great question. That's an improvement I'd been meaning to make. Now available in `v0.6.1`. Fetch the latest with `pip install -U markovify`, and see the instructions here: https://github.com/jsvine/markovify#generating-markovifytext-models-from-very-large-corpora

Does that improve performance for you?

**Comment by rivermont** [comment]
Awesome, thank you!
I accidentally overwrote the large corpus yesterday; am re-generating it now. Will test performance in a few hours once it's done.

**Comment by rivermont** [comment]
While it doesn't load the corpus into memory the model is still too large for my 16GB of RAM. This is not exactly surprising as the model file is 30GB. I'll see about creating models from chunks of the corpus and combining them.

**Comment by briennakh** [comment]
@rivermont did you get to test creating models from chunks of the corpus and combining them?
