### ISSUE TITLE
AttributeError: 'Text' object has no attribute 'parsed_sentences'

### ISSUE THREAD

**Issue by lormayna** [jsvine/markovify#79]
Hi, I'm trying to combine some text models and this is the erro that I got.

`Traceback (most recent call last):
  File "generate_files.py", line 57, in <module>
    main()
  File "generate_files.py", line 49, in main
    combined_model = markovify.combine([last_day_model, last_week_model, last_month_model, last_six_month_model], [10, 5, 2, 1])
  File "/home/lorenzo/project/m5bot/lib/python3.4/site-packages/markovify/utils.py", line 50, in combine
    combined_sentences += m.parsed_sentences
AttributeError: 'Text' object has no attribute 'parsed_sentences'`

**Comment by jsvine** [comment]
Thanks to @thallada, there's a fix available in `0.6.3`, which is now available via PyPi. If you upgrade the library to `0.6.3`, do you still get the error?

**Comment by lormayna** [comment]
After the upgrade it's working fine.
Thank you for the quick reply.
