### ISSUE TITLE
markovify.Text(...) giving an error

### ISSUE THREAD

**Issue by JPGHub** [jsvine/markovify#89]
markovify.Text(...) method give an error:
AttributeError: 'module' object has no attribute 'Text'

I'm using python 2.7...I just did pip install markovify and tried to run the sample code.

**Comment by jsvine** [comment]
Tests seem to be running fine on Python 2.7: https://travis-ci.org/jsvine/markovify/jobs/308788048

Can you share the full list of steps you're taking, including the code?

**Comment by JPGHub** [comment]
Thanks for the prompt reply!

The issue is resolved now. I named my script as markovify.py which was causing the issue.
